# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-01-23 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ]

    operations = [
    ]
