# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-03-27 22:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190123_1435'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='selectedproposal',
            field=models.CharField(default=b'Select a proposal', max_length=64, verbose_name=b'Select a proposal'),
        ),
    ]
