# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2019-04-25 20:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20190425_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='deny',
            field=models.BooleanField(default=False),
        ),
    ]
